[package]
name = "text-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
fontdue.workspace = true
rustybuzz.workspace = true
ttf-parser.workspace = true
serde.workspace = true
rayon.workspace = true
transform-math = { path = "../transform-math" }
raster-cpu = { path = "../raster-cpu" }
